QUANTITY_ZERO = 0

VARIETY_REG = "regular"
VARIETY_AMO = "amo"

EXCHANGE_NFO = "NFO"
EXCHANGE_NSE = "NSE"

TRANSACTION_TYPE_SELL = "SELL"
TRANSACTION_TYPE_BUY = "BUY"

PRODUCT_MIS = "MIS"
PRODUCT_NRML = "NRML"

ORDER_TYPE_SL = "SL"
ORDER_TYPE_LIMIT = "LIMIT"

VALIDITY_DAY = "DAY"
VALIDITY_TTL_NONE = None
DISCLOSED_QUANTITY_NONE = None

PARENT_ID_NONE = None

ORDER_STATUS_OPEN = "OPEN"
ORDER_STATUS_OPEN_PENDING = "OPEN PENDING"
ORDER_STATUS_AMO_REQ = "AMO REQ RECEIVED"
ORDER_STATUS_COMPLETE = "COMPLETE"
ORDER_STATUS_TRIGGER_PENDING = "TRIGGER PENDING"


LIMIT_PRICE_OFFSET = 7.7
LOSS_PRICE_OFFSET = 1.7

LOSS_PRICE_GAIN = 4
LOSS_PRICE_GAIN_OFFSET = 1

TRIGGER_PRICE_OFFSET = 1
LOWER_BAND_PRICE_OFFSET = 2

FUNDS = 10000
THRESHOLD_POINTS = 7